---
development:
  cloud_name: dhybx2kd3
  api_key: '754658891438352'
  api_secret: X2a1RW97z-eVUZQCleS0tQKuWt0
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dhybx2kd3
  api_key: '754658891438352'
  api_secret: X2a1RW97z-eVUZQCleS0tQKuWt0
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dhybx2kd3
  api_key: '754658891438352'
  api_secret: X2a1RW97z-eVUZQCleS0tQKuWt0
  enhance_image_tag: true
  static_file_support: false
